-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 21:15:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `DOB` DATE NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Zip` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `AccountCreationDate` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `SecurityQuestion1` TINYTEXT NOT NULL,
  `Answer1` VARCHAR(45) NOT NULL,
  `SecurityQuestion2` TINYTEXT NOT NULL,
  `Answer2` VARCHAR(45) NOT NULL,
  `SecurityQuestion3` TINYTEXT NOT NULL,
  `Answer3` VARCHAR(45) NOT NULL,
  `Recently Played` VARCHAR(45) NULL,
  `Recent Play Time` TIMESTAMP NULL,
  `Last Played Date` DATE NULL,
  `Total Time Played` TIMESTAMP NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;

insert into `mydb`.`User` (`UserID`, `UserName`, `FirstName`, `LastName`,`Email`, `DOB`,`PhoneNumber`, `City`, `State`, `Zip`, `Country`, `AccountCreationDate`, `password`, `SecurityQuestion1`, `Answer1`, `SecurityQuestion2`, `Answer2`, `SecurityQuestion3`, `Answer3`, `Recently Played`, `Recent Play Time`, `Last Played Date`, `Total Time Played` ) values
    
    (10000,'legend','Jack','Uber','jackuber@gmail.com','1998-09-06',3035550555,'Denver','CO', null, 'United States of America','2021-02-21','superSticious18$','Whats your favorite pets name?','buddy','What was your first car?','volvo','Whats your mothers maiden name?','nicole', null, null, null , null),
    (10001,'ace','Fatty','McPatty','fatace@comcast.net','1996-09-17',3035610394,'Boulder','CO', null,'United States of America','2021-02-21','stankleg420','Whats your mothers maiden name?','susan','Whats your favorite pets name?','dotson','What was the name of the first girl you kissed?','nicole',null, null, null , null),
    (10002,'spiderboy','Terance','Lebron','terance11@yahoo.com','1997-03-20',7202259908,'Centennial','AZ',null,'United States of America','2021-02-22','yeeyeepriate','What was your first car?','jeep grand cherokee','What street did you grow up on?','jupiter drive','What was the name of the first girl you kissed?','jennifer',null, null, null , null),
	(10003,'yaggayeet','Harry','Kim','harry.kim@gmail.com','1942-07-20',7204305567,'Littleton', 'AK', null, 'United States of America','2021-02-22','password11','What is your favorite teachers name?','mr. bronkowski','What street did you grow up on?','baker avenue','Whats your favorite pets name?','jackie',null, null, null , null),
    (10004,'zelda','Nicole','Rossling','nikkyrossling@gmail.com','1991-03-04',7208885252,'Littleton', 'AK', null,'United States of America','2021-02-22','myfavoritepassword','Whats your favorite pets name?','dodger','What was the name of the first girl you kissed?','ashley sparko','What is your favorite teachers name?','kelly walsh',null, null, null , null);
    
CREATE UNIQUE INDEX `UserName_UNIQUE` ON `mydb`.`User` (`UserName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Games` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Games` (
  `GameID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Description` TEXT(1000) NULL,
  `Multiplayer` TINYINT NULL,
  `ESRB_Rating` VARCHAR(4) NULL,
  `DateReleased` DATE NULL,
  `Publisher` VARCHAR(45) NULL,
  `Developer` VARCHAR(45) NULL,
  `Notes` TINYTEXT NULL,
  `CommunityReview` DECIMAL(3,1) NULL,
  `IGNReview` DECIMAL(3,1) NULL,
  `Platform` VARCHAR(45) NULL,
  PRIMARY KEY (`GameID`))
ENGINE = InnoDB;

insert into `mydb`.`Games`(`GameID`, `Title`, `Description`, `Multiplayer`, `ESRB_Rating`, `DateReleased`, `Publisher`,  `Developer` , `Notes`, `CommunityReview`, `IGNReview`, `Platform`) values
	(1, 'Zelda', 'Adventure Game', false, 'E10+', '1986-02-21','Nintendo', 'Nintendo', null, 9.8, 10.0,'NES'),
	(2, 'Rick James', 'SIM', false, 'T', '2003-02-21','Rare', 'Microsoft', null, 6.8, 5.0,'computer'),
	(3, 'Book Worm', 'Education', true, 'E', '1999-05-01','THQ', 'Activision', null, 6.0, 7.2,'computer'),
    (4, 'Mario Odessey', 'Collection Game', True, 'E10+', '2016-08-13','Nintendo', 'Nintendo', null, 9.7, 10.0,'Nintendo Switch'),
    (5, 'Zelda Breath of the Wild', 'Adventure Game', false, 'E10+', '2016-02-21','Nintendo', 'Nintendo', null, 9.8, 10.0,'Nintendo Switch'),
    (6, 'Counter Strike', 'Multiplayer Shooter', true, 'M', '2012-04-20','Valve', 'Valve', null, 8.3, 7.5,'Computer'),
    (7, "Spongebob's Atlantis Squarepantis", 'Adventure Game', false, 'E10+', '2009-11-12','THQ', 'Activision', null, 5.6, 10.0,'Nintendo DS'),
    (8, "Woe was I", 'Walking Sim', false, 'RP', '2021-03-02','Dolphin Corp.', 'Steam', null, 0.1, 1.2,'Computer'),
    (9, 'Pokemon Go', 'MMORPG', true, 'E10+', '2016-02-21','Atlantic', 'Nintendo', null, 9.0, 8.0,'Mobile');
-- -----------------------------------------------------
-- Table `mydb`.`UserGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserGame` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserGame` (
  `UserID` INT NOT NULL,
  `GameID` INT NOT NULL,
  `UserIGN` DECIMAL(2,1) NULL,
  `UserReview` TEXT(1000) NULL,
  `UserRating` DECIMAL(2,1) NULL,
  `LastTimePlayed` DATE NULL,
  `Notes` TEXT(1000) NULL,
  `TotalTimePlayed` TIMESTAMP(6) NULL,
  `User_UserID` INT NOT NULL,
  `Games_GameID` INT NOT NULL,
  PRIMARY KEY (`UserID`, `GameID`, `User_UserID`, `Games_GameID`),
  CONSTRAINT `fk_UserGame_User`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserGame_Games1`
    FOREIGN KEY (`Games_GameID`)
    REFERENCES `mydb`.`Games` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into `mydb`.`UserGame`(`UserID`, `GameID`, `UserIGN`,  `UserReview`,  `UserRating`, `LastTimePlayed`, `Notes`, `TotalTimePlayed`,`User_UserID`,`Games_GameID`) values
	(10000, 5, null, null, null, null, null, null, 10000, 5),
    (10000, 3, null, null, null, null, null, null,10000, 3),
    (10000, 8, null, null, null, null, null, null, 10000, 8),
    (10001, 8, null, null, null, null, null, null, 10001, 8),
    (10001, 0, null, null, null, null, null, null, 10001, 0),
	(10001, 1, null, null, null, null, null, null, 10001, 1),
    (10001, 2, null, null, null, null, null, null, 10001, 2),
    (10001, 4, null, null, null, null, null, null, 10001, 4),
    (10002, 6, null, null, null, null, null, null, 10002, 6),
    (10002, 9, null, null, null, null, null, null, 10002, 9),
    (10002, 7, null, null, null, null, null, null, 10002, 7),
    (10002, 4, null, null, null, null, null, null, 10002, 4),
    (10003, 4, null, null, null, null, null, null, 10003, 4),
    (10003, 5, null, null, null, null, null, null, 10003, 5),
	(10003, 6, null, null, null, null, null, null, 10003, 6),
    (10003, 7, null, null, null, null, null, null, 10003, 7),
    (10004, 7, null, null, null, null, null, null, 10004, 7),
    (10004, 9, null, null, null, null, null, null, 10004, 9);

CREATE INDEX `fk_UserGame_User_idx` ON `mydb`.`UserGame` (`User_UserID` ASC) VISIBLE;

CREATE INDEX `fk_UserGame_Games1_idx` ON `mydb`.`UserGame` (`Games_GameID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `Tags` INT NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameTags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameTags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameTags` (
  `GameID` INT NOT NULL,
  `TagID` VARCHAR(45) NOT NULL,
  `Games_GameID` INT NOT NULL,
  `Tags_Tags` INT NOT NULL,
  PRIMARY KEY (`GameID`, `TagID`, `Games_GameID`, `Tags_Tags`),
  CONSTRAINT `fk_GameTags_Games1`
    FOREIGN KEY (`Games_GameID`)
    REFERENCES `mydb`.`Games` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GameTags_Tags1`
    FOREIGN KEY (`Tags_Tags`)
    REFERENCES `mydb`.`Tags` (`Tags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GameTags_Games1_idx` ON `mydb`.`GameTags` (`Games_GameID` ASC) VISIBLE;

CREATE INDEX `fk_GameTags_Tags1_idx` ON `mydb`.`GameTags` (`Tags_Tags` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`GameAchievements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameAchievements` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameAchievements` (
  `GameID` INT NOT NULL,
  `AchievementId` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Games_GameID` INT NOT NULL,
  PRIMARY KEY (`AchievementId`, `GameID`, `Games_GameID`),
  CONSTRAINT `fk_GameAchievements_Games1`
    FOREIGN KEY (`Games_GameID`)
    REFERENCES `mydb`.`Games` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GameAchievements_Games1_idx` ON `mydb`.`GameAchievements` (`Games_GameID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`UserAchievement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UserAchievement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UserAchievement` (
  `UserID` INT NOT NULL,
  `GameID` INT NOT NULL,
  `AchievementID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Completed` TINYINT NOT NULL,
  `Date Completed` DATE NULL,
  `UserGame_UserID` INT NOT NULL,
  `UserGame_GameID` INT NOT NULL,
  `UserGame_User_UserID` INT NOT NULL,
  `UserGame_Games_GameID` INT NOT NULL,
  `GameAchievements_AchievementId` VARCHAR(45) NOT NULL,
  `GameAchievements_GameID` INT NOT NULL,
  `GameAchievements_Games_GameID` INT NOT NULL,
  PRIMARY KEY (`UserID`, `GameID`, `AchievementID`, `UserGame_UserID`, `UserGame_GameID`, `UserGame_User_UserID`, `UserGame_Games_GameID`, `GameAchievements_AchievementId`, `GameAchievements_GameID`, `GameAchievements_Games_GameID`),
  CONSTRAINT `fk_UserAchievement_UserGame1`
    FOREIGN KEY (`UserGame_UserID` , `UserGame_GameID` , `UserGame_User_UserID` , `UserGame_Games_GameID`)
    REFERENCES `mydb`.`UserGame` (`UserID` , `GameID` , `User_UserID` , `Games_GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserAchievement_GameAchievements1`
    FOREIGN KEY (`GameAchievements_AchievementId` , `GameAchievements_GameID` , `GameAchievements_Games_GameID`)
    REFERENCES `mydb`.`GameAchievements` (`AchievementId` , `GameID` , `Games_GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_UserAchievement_UserGame1_idx` ON `mydb`.`UserAchievement` (`UserGame_UserID` ASC, `UserGame_GameID` ASC, `UserGame_User_UserID` ASC, `UserGame_Games_GameID` ASC) VISIBLE;

CREATE INDEX `fk_UserAchievement_GameAchievements1_idx` ON `mydb`.`UserAchievement` (`GameAchievements_AchievementId` ASC, `GameAchievements_GameID` ASC, `GameAchievements_Games_GameID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
